// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package protocols;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageID}
   */
  public enum MessageID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_BEST_MOVE = 0;</code>
     */
    GET_BEST_MOVE(0),
    /**
     * <code>MOVE_PIECE = 1;</code>
     */
    MOVE_PIECE(1),
    /**
     * <code>GET_VALID_MOVES = 2;</code>
     */
    GET_VALID_MOVES(2),
    /**
     * <code>FIND_BEST = 3;</code>
     */
    FIND_BEST(3),
    /**
     * <code>VALID_MOVES_RESPONSE = 4;</code>
     */
    VALID_MOVES_RESPONSE(4),
    /**
     * <code>FIND_BEST_RESPONSE = 5;</code>
     */
    FIND_BEST_RESPONSE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GET_BEST_MOVE = 0;</code>
     */
    public static final int GET_BEST_MOVE_VALUE = 0;
    /**
     * <code>MOVE_PIECE = 1;</code>
     */
    public static final int MOVE_PIECE_VALUE = 1;
    /**
     * <code>GET_VALID_MOVES = 2;</code>
     */
    public static final int GET_VALID_MOVES_VALUE = 2;
    /**
     * <code>FIND_BEST = 3;</code>
     */
    public static final int FIND_BEST_VALUE = 3;
    /**
     * <code>VALID_MOVES_RESPONSE = 4;</code>
     */
    public static final int VALID_MOVES_RESPONSE_VALUE = 4;
    /**
     * <code>FIND_BEST_RESPONSE = 5;</code>
     */
    public static final int FIND_BEST_RESPONSE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageID valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageID forNumber(int value) {
      switch (value) {
        case 0: return GET_BEST_MOVE;
        case 1: return MOVE_PIECE;
        case 2: return GET_VALID_MOVES;
        case 3: return FIND_BEST;
        case 4: return VALID_MOVES_RESPONSE;
        case 5: return FIND_BEST_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageID>() {
            public MessageID findValueByNumber(int number) {
              return MessageID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocols.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageID[] VALUES = values();

    public static MessageID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto*\204\001\n\tMessageID\022\021\n\rGET_BEST" +
      "_MOVE\020\000\022\016\n\nMOVE_PIECE\020\001\022\023\n\017GET_VALID_MOV" +
      "ES\020\002\022\r\n\tFIND_BEST\020\003\022\030\n\024VALID_MOVES_RESPO" +
      "NSE\020\004\022\026\n\022FIND_BEST_RESPONSE\020\005B\023\n\tprotoco" +
      "lsB\006Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
