// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package protocols;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageID}
   */
  public enum MessageID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GET_BEST_MOVE = 0;</code>
     */
    GET_BEST_MOVE(0),
    /**
     * <code>MOVE_PIECE = 1;</code>
     */
    MOVE_PIECE(1),
    /**
     * <code>GET_VALID_MOVES = 2;</code>
     */
    GET_VALID_MOVES(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GET_BEST_MOVE = 0;</code>
     */
    public static final int GET_BEST_MOVE_VALUE = 0;
    /**
     * <code>MOVE_PIECE = 1;</code>
     */
    public static final int MOVE_PIECE_VALUE = 1;
    /**
     * <code>GET_VALID_MOVES = 2;</code>
     */
    public static final int GET_VALID_MOVES_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageID valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageID forNumber(int value) {
      switch (value) {
        case 0: return GET_BEST_MOVE;
        case 1: return MOVE_PIECE;
        case 2: return GET_VALID_MOVES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageID>() {
            public MessageID findValueByNumber(int number) {
              return MessageID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocols.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageID[] VALUES = values();

    public static MessageID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageID)
  }

  public interface TestEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TestEnum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 baseval = 1;</code>
     * @return The baseval.
     */
    int getBaseval();

    /**
     * <code>int32 nextval = 2;</code>
     * @return The nextval.
     */
    int getNextval();
  }
  /**
   * Protobuf type {@code TestEnum}
   */
  public static final class TestEnum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TestEnum)
      TestEnumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestEnum.newBuilder() to construct.
    private TestEnum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestEnum() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestEnum();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestEnum(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              baseval_ = input.readInt32();
              break;
            }
            case 16: {

              nextval_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.Common.internal_static_TestEnum_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.Common.internal_static_TestEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.Common.TestEnum.class, protocols.Common.TestEnum.Builder.class);
    }

    public static final int BASEVAL_FIELD_NUMBER = 1;
    private int baseval_;
    /**
     * <code>int32 baseval = 1;</code>
     * @return The baseval.
     */
    @java.lang.Override
    public int getBaseval() {
      return baseval_;
    }

    public static final int NEXTVAL_FIELD_NUMBER = 2;
    private int nextval_;
    /**
     * <code>int32 nextval = 2;</code>
     * @return The nextval.
     */
    @java.lang.Override
    public int getNextval() {
      return nextval_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (baseval_ != 0) {
        output.writeInt32(1, baseval_);
      }
      if (nextval_ != 0) {
        output.writeInt32(2, nextval_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (baseval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, baseval_);
      }
      if (nextval_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, nextval_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.Common.TestEnum)) {
        return super.equals(obj);
      }
      protocols.Common.TestEnum other = (protocols.Common.TestEnum) obj;

      if (getBaseval()
          != other.getBaseval()) return false;
      if (getNextval()
          != other.getNextval()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BASEVAL_FIELD_NUMBER;
      hash = (53 * hash) + getBaseval();
      hash = (37 * hash) + NEXTVAL_FIELD_NUMBER;
      hash = (53 * hash) + getNextval();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.Common.TestEnum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.TestEnum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.TestEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.TestEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.TestEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.TestEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.TestEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.TestEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.TestEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.Common.TestEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.TestEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.TestEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.Common.TestEnum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TestEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TestEnum)
        protocols.Common.TestEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.Common.internal_static_TestEnum_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.Common.internal_static_TestEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.Common.TestEnum.class, protocols.Common.TestEnum.Builder.class);
      }

      // Construct using protocols.Common.TestEnum.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        baseval_ = 0;

        nextval_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.Common.internal_static_TestEnum_descriptor;
      }

      @java.lang.Override
      public protocols.Common.TestEnum getDefaultInstanceForType() {
        return protocols.Common.TestEnum.getDefaultInstance();
      }

      @java.lang.Override
      public protocols.Common.TestEnum build() {
        protocols.Common.TestEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocols.Common.TestEnum buildPartial() {
        protocols.Common.TestEnum result = new protocols.Common.TestEnum(this);
        result.baseval_ = baseval_;
        result.nextval_ = nextval_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.Common.TestEnum) {
          return mergeFrom((protocols.Common.TestEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.Common.TestEnum other) {
        if (other == protocols.Common.TestEnum.getDefaultInstance()) return this;
        if (other.getBaseval() != 0) {
          setBaseval(other.getBaseval());
        }
        if (other.getNextval() != 0) {
          setNextval(other.getNextval());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.Common.TestEnum parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.Common.TestEnum) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int baseval_ ;
      /**
       * <code>int32 baseval = 1;</code>
       * @return The baseval.
       */
      @java.lang.Override
      public int getBaseval() {
        return baseval_;
      }
      /**
       * <code>int32 baseval = 1;</code>
       * @param value The baseval to set.
       * @return This builder for chaining.
       */
      public Builder setBaseval(int value) {
        
        baseval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 baseval = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBaseval() {
        
        baseval_ = 0;
        onChanged();
        return this;
      }

      private int nextval_ ;
      /**
       * <code>int32 nextval = 2;</code>
       * @return The nextval.
       */
      @java.lang.Override
      public int getNextval() {
        return nextval_;
      }
      /**
       * <code>int32 nextval = 2;</code>
       * @param value The nextval to set.
       * @return This builder for chaining.
       */
      public Builder setNextval(int value) {
        
        nextval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nextval = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNextval() {
        
        nextval_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TestEnum)
    }

    // @@protoc_insertion_point(class_scope:TestEnum)
    private static final protocols.Common.TestEnum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.Common.TestEnum();
    }

    public static protocols.Common.TestEnum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestEnum>
        PARSER = new com.google.protobuf.AbstractParser<TestEnum>() {
      @java.lang.Override
      public TestEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestEnum(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestEnum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestEnum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocols.Common.TestEnum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidatePositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ValidatePosition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 validateCount = 1;</code>
     * @return The validateCount.
     */
    int getValidateCount();

    /**
     * <code>bool validate = 2;</code>
     * @return The validate.
     */
    boolean getValidate();
  }
  /**
   * Protobuf type {@code ValidatePosition}
   */
  public static final class ValidatePosition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ValidatePosition)
      ValidatePositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidatePosition.newBuilder() to construct.
    private ValidatePosition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidatePosition() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ValidatePosition();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidatePosition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              validateCount_ = input.readInt32();
              break;
            }
            case 16: {

              validate_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.Common.internal_static_ValidatePosition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.Common.internal_static_ValidatePosition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.Common.ValidatePosition.class, protocols.Common.ValidatePosition.Builder.class);
    }

    public static final int VALIDATECOUNT_FIELD_NUMBER = 1;
    private int validateCount_;
    /**
     * <code>int32 validateCount = 1;</code>
     * @return The validateCount.
     */
    @java.lang.Override
    public int getValidateCount() {
      return validateCount_;
    }

    public static final int VALIDATE_FIELD_NUMBER = 2;
    private boolean validate_;
    /**
     * <code>bool validate = 2;</code>
     * @return The validate.
     */
    @java.lang.Override
    public boolean getValidate() {
      return validate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (validateCount_ != 0) {
        output.writeInt32(1, validateCount_);
      }
      if (validate_ != false) {
        output.writeBool(2, validate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (validateCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, validateCount_);
      }
      if (validate_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, validate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.Common.ValidatePosition)) {
        return super.equals(obj);
      }
      protocols.Common.ValidatePosition other = (protocols.Common.ValidatePosition) obj;

      if (getValidateCount()
          != other.getValidateCount()) return false;
      if (getValidate()
          != other.getValidate()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALIDATECOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getValidateCount();
      hash = (37 * hash) + VALIDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getValidate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.Common.ValidatePosition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.ValidatePosition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.ValidatePosition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.ValidatePosition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.Common.ValidatePosition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.ValidatePosition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.Common.ValidatePosition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValidatePosition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ValidatePosition)
        protocols.Common.ValidatePositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.Common.internal_static_ValidatePosition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.Common.internal_static_ValidatePosition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.Common.ValidatePosition.class, protocols.Common.ValidatePosition.Builder.class);
      }

      // Construct using protocols.Common.ValidatePosition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        validateCount_ = 0;

        validate_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.Common.internal_static_ValidatePosition_descriptor;
      }

      @java.lang.Override
      public protocols.Common.ValidatePosition getDefaultInstanceForType() {
        return protocols.Common.ValidatePosition.getDefaultInstance();
      }

      @java.lang.Override
      public protocols.Common.ValidatePosition build() {
        protocols.Common.ValidatePosition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocols.Common.ValidatePosition buildPartial() {
        protocols.Common.ValidatePosition result = new protocols.Common.ValidatePosition(this);
        result.validateCount_ = validateCount_;
        result.validate_ = validate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.Common.ValidatePosition) {
          return mergeFrom((protocols.Common.ValidatePosition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.Common.ValidatePosition other) {
        if (other == protocols.Common.ValidatePosition.getDefaultInstance()) return this;
        if (other.getValidateCount() != 0) {
          setValidateCount(other.getValidateCount());
        }
        if (other.getValidate() != false) {
          setValidate(other.getValidate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.Common.ValidatePosition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.Common.ValidatePosition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int validateCount_ ;
      /**
       * <code>int32 validateCount = 1;</code>
       * @return The validateCount.
       */
      @java.lang.Override
      public int getValidateCount() {
        return validateCount_;
      }
      /**
       * <code>int32 validateCount = 1;</code>
       * @param value The validateCount to set.
       * @return This builder for chaining.
       */
      public Builder setValidateCount(int value) {
        
        validateCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 validateCount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidateCount() {
        
        validateCount_ = 0;
        onChanged();
        return this;
      }

      private boolean validate_ ;
      /**
       * <code>bool validate = 2;</code>
       * @return The validate.
       */
      @java.lang.Override
      public boolean getValidate() {
        return validate_;
      }
      /**
       * <code>bool validate = 2;</code>
       * @param value The validate to set.
       * @return This builder for chaining.
       */
      public Builder setValidate(boolean value) {
        
        validate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool validate = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidate() {
        
        validate_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ValidatePosition)
    }

    // @@protoc_insertion_point(class_scope:ValidatePosition)
    private static final protocols.Common.ValidatePosition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.Common.ValidatePosition();
    }

    public static protocols.Common.ValidatePosition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidatePosition>
        PARSER = new com.google.protobuf.AbstractParser<ValidatePosition>() {
      @java.lang.Override
      public ValidatePosition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidatePosition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidatePosition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidatePosition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocols.Common.ValidatePosition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovePieceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MovePiece)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 from = 1;</code>
     * @return The from.
     */
    int getFrom();

    /**
     * <code>int32 to = 2;</code>
     * @return The to.
     */
    int getTo();
  }
  /**
   * Protobuf type {@code MovePiece}
   */
  public static final class MovePiece extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MovePiece)
      MovePieceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MovePiece.newBuilder() to construct.
    private MovePiece(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovePiece() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MovePiece();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovePiece(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              from_ = input.readInt32();
              break;
            }
            case 16: {

              to_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocols.Common.internal_static_MovePiece_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocols.Common.internal_static_MovePiece_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocols.Common.MovePiece.class, protocols.Common.MovePiece.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private int from_;
    /**
     * <code>int32 from = 1;</code>
     * @return The from.
     */
    @java.lang.Override
    public int getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private int to_;
    /**
     * <code>int32 to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public int getTo() {
      return to_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0) {
        output.writeInt32(1, from_);
      }
      if (to_ != 0) {
        output.writeInt32(2, to_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, from_);
      }
      if (to_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, to_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocols.Common.MovePiece)) {
        return super.equals(obj);
      }
      protocols.Common.MovePiece other = (protocols.Common.MovePiece) obj;

      if (getFrom()
          != other.getFrom()) return false;
      if (getTo()
          != other.getTo()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocols.Common.MovePiece parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.MovePiece parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.MovePiece parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.MovePiece parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.MovePiece parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocols.Common.MovePiece parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocols.Common.MovePiece parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.MovePiece parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.MovePiece parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocols.Common.MovePiece parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocols.Common.MovePiece parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocols.Common.MovePiece parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocols.Common.MovePiece prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MovePiece}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MovePiece)
        protocols.Common.MovePieceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocols.Common.internal_static_MovePiece_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocols.Common.internal_static_MovePiece_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocols.Common.MovePiece.class, protocols.Common.MovePiece.Builder.class);
      }

      // Construct using protocols.Common.MovePiece.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0;

        to_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocols.Common.internal_static_MovePiece_descriptor;
      }

      @java.lang.Override
      public protocols.Common.MovePiece getDefaultInstanceForType() {
        return protocols.Common.MovePiece.getDefaultInstance();
      }

      @java.lang.Override
      public protocols.Common.MovePiece build() {
        protocols.Common.MovePiece result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protocols.Common.MovePiece buildPartial() {
        protocols.Common.MovePiece result = new protocols.Common.MovePiece(this);
        result.from_ = from_;
        result.to_ = to_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocols.Common.MovePiece) {
          return mergeFrom((protocols.Common.MovePiece)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocols.Common.MovePiece other) {
        if (other == protocols.Common.MovePiece.getDefaultInstance()) return this;
        if (other.getFrom() != 0) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != 0) {
          setTo(other.getTo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocols.Common.MovePiece parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocols.Common.MovePiece) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int from_ ;
      /**
       * <code>int32 from = 1;</code>
       * @return The from.
       */
      @java.lang.Override
      public int getFrom() {
        return from_;
      }
      /**
       * <code>int32 from = 1;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(int value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 from = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        
        from_ = 0;
        onChanged();
        return this;
      }

      private int to_ ;
      /**
       * <code>int32 to = 2;</code>
       * @return The to.
       */
      @java.lang.Override
      public int getTo() {
        return to_;
      }
      /**
       * <code>int32 to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(int value) {
        
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        
        to_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MovePiece)
    }

    // @@protoc_insertion_point(class_scope:MovePiece)
    private static final protocols.Common.MovePiece DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocols.Common.MovePiece();
    }

    public static protocols.Common.MovePiece getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovePiece>
        PARSER = new com.google.protobuf.AbstractParser<MovePiece>() {
      @java.lang.Override
      public MovePiece parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovePiece(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovePiece> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovePiece> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protocols.Common.MovePiece getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TestEnum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TestEnum_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidatePosition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidatePosition_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MovePiece_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MovePiece_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\",\n\010TestEnum\022\017\n\007baseval\030\001 " +
      "\001(\005\022\017\n\007nextval\030\002 \001(\005\";\n\020ValidatePosition" +
      "\022\025\n\rvalidateCount\030\001 \001(\005\022\020\n\010validate\030\002 \001(" +
      "\010\"%\n\tMovePiece\022\014\n\004from\030\001 \001(\005\022\n\n\002to\030\002 \001(\005" +
      "*C\n\tMessageID\022\021\n\rGET_BEST_MOVE\020\000\022\016\n\nMOVE" +
      "_PIECE\020\001\022\023\n\017GET_VALID_MOVES\020\002B\023\n\tprotoco" +
      "lsB\006Commonb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TestEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TestEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TestEnum_descriptor,
        new java.lang.String[] { "Baseval", "Nextval", });
    internal_static_ValidatePosition_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ValidatePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidatePosition_descriptor,
        new java.lang.String[] { "ValidateCount", "Validate", });
    internal_static_MovePiece_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MovePiece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MovePiece_descriptor,
        new java.lang.String[] { "From", "To", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
